# -*- coding: utf-8 -*-


class MachineConfig:
    SETPOINT = -18.0
    DIFERENCIAL = 2.0
 

    ANTI_REARME_SEGUNDOS = 5

    INTERVALO_DEGELO_SEGUNDOS = 60
    PASSO_VALVULA_DEGELO_SEGUNDOS = 2
    TEMPO_MAXIMO_DEGELO_SEGUNDOS = 60
    TEMPO_GOTEJAMENTO_SEGUNDOS = 10

    ABERTURA_INICIAL_DEGELO = 50
    INCREMENTO_VALVULA_DEGELO = 10
    TEMPERATURA_FIM_DEGELO = 8.0

    FAN2_ON_PSI = 270.0
    FAN2_OFF_PSI = 240.0

    TEMPO_MAXIMO_OLEO_SEGUNDOS = 30