from enum import Enum

class MachineState(Enum):
    ST_DESLIGADA = "DESLIGADA"
    ST_INICIALIZANDO = "INICIALIZANDO"
    ST_VERIFICANDO = "VERIFICANDO"
    ST_PRONTA = "PRONTA"
    ST_REFRIGERANDO = "REFRIGERANDO"
    ST_DEGELO = "DEGELO"
    ST_ALARME = "ALARME"
    ST_BLOQUEADA = "BLOQUEADA"
